# Generated by Django 4.2.13 on 2024-06-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img_path', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
