# Generated by Django 5.0.6 on 2024-06-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.pais')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(default='Arica y Parinacota', on_delete=django.db.models.deletion.CASCADE, to='registro.region'),
            preserve_default=False,
        ),
    ]
