# Generated by Django 5.0.6 on 2024-06-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_region_comuna_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
