# Generated by Django 5.0.6 on 2024-06-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_delete_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comuna',
            old_name='region',
            new_name='id_region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='pais',
            new_name='id_pais',
        ),
        migrations.AlterField(
            model_name='comuna',
            name='id_comuna',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pais',
            name='id_pais',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id_region',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
