# Generated by Django 5.0.6 on 2024-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_remove_cliente_nombre_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='nombre', max_length=100),
        ),
    ]
