# Generated by Django 5.0.6 on 2024-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
