# Generated by Django 5.0.6 on 2024-06-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_alter_cliente_email_alter_cliente_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ciudad',
            new_name='region',
        ),
    ]
