# Generated by Django 5.0.6 on 2024-06-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_rename_ciudad_cliente_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
