# Generated by Django 4.2.13 on 2024-06-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
