# Generated by Django 4.2.13 on 2024-06-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_alter_cliente_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='username',
        ),
    ]
