# Generated by Django 4.2.13 on 2024-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_remove_cliente_password_remove_cliente_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
